### ISSUE TITLE
add `graphql-mesh/graphql`

### ISSUE THREAD

**Issue by hulucc** [onelittlenightmusic/graphql-mesh-docker#2]
pls support `graphql` source

**Comment by onelittlenightmusic** [comment]
Oops, I missed it. Thank you for the comment.

**Comment by onelittlenightmusic** [comment]
Included `graphql-mesh/graphql` in Dockerfile-all 
https://github.com/onelittlenightmusic/graphql-mesh-docker/commit/5826bfe0b32701c4a44294424b8f3ddfdc37bd2a#diff-526055d4383cf74ef9bfa3eee44cf474e895531543156679cf000deeb2ad73dc
You can pull `hiroyukiosaki/graphql-mesh:latest-all` image to use `graphql-mesh/graphql`.
